routes/web.php
	Route::get('customar/dashboard','CustomarController@cusDashboard')->name('customar.cusdashboard');
	Route::get('customar/profile','CustomarController@cusProfile')->name('customar.profile');
	Route::post('customar/profile-update','CustomarController@cusProfileUpdate')->name('customar.profile.update');
	Route::get('customar/password-change','CustomarController@cusPassword')->name('customar.password');
	Route::post('customar/password-change/update','CustomarController@cusPasswordUpdate')->name('customar.password.update');
	Route::post('customar/store','CustomarController@store')->name('customar.store');
	Route::get('customar/login','CustomarController@cusLogin')->name('customar.cuslogin');
	Route::get('customar/logout','CustomarController@cusLogout')->name('customar.logout');
	Route::get('customar/order','CustomarController@cusOrder')->name('customar.order');
	Route::get('/order-view/{id}','CustomarController@orderView')->name('customar.order.view');
	Route::get('/order-view/pdf/{id}','CustomarController@orderPdf')->name('customar.order.list.pdf');
	//customar verify
	Route::get('customar-account/verify','CustomarController@customarVerify')->name('customar.verify');
	Route::post('customar/verify-success','CustomarController@cusVerify')->name('customar.verify.completes');

	// shipping and payment 
	Route::post('/shipping-store','ShippingController@store')->name('shipping.store');
	Route::get('/payment','ShippingController@payment')->name('customar.payment');

	// contact routes
	Route::get('/contact','ContactController@index')->name('contact.index');
	Route::post('/contact-store','ContactController@store')->name('contact.store');

	// subscriber routes
	Route::post('/subscribe','SubscribeController@store')->name('subscribe.store');

	// order routes
	Route::post('/order-store/by-cash','OrderController@storeByCash')->name('order.store.by.cash');
	Route::post('/order-store/by-bkash','OrderController@storeBybkash')->name('order.store.by.bkash');

	// contact routes
	Route::get('/search-products','SearchController@searchProduct')->name('search.index');

	// default routes | about, faqs, helps, 
	Route::get('/abouts','DefaultController@aboutPages')->name('about.page');
	Route::get('/faqs','DefaultController@faqsPages')->name('faqs.page');
	Route::get('/helps','DefaultController@helpPages')->name('help.page');
	Route::get('/terms-of-use','DefaultController@termsPages')->name('termsofuse.page');
	Route::get('/privacy-policy','DefaultController@privacyPages')->name('privacy.page');


});






Auth::routes();


Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin', 'middleware'=>['auth','admin']],function(){

	Route::get('dashboard','AdminDashboardController@index')->name('dashboard');

	//brand proccess routes ajax
	Route::get('brand/list','BrandController@index')->name('brand.index');
	Route::get('brand/alldata','BrandController@allData')->name('brand.alldata');
	Route::post('brand/store','BrandController@store')->name('brand.store');
	Route::get('brand/edit/{id}','BrandController@edit')->name('brand.edit');
	Route::post('brand/update/{id}','BrandController@update')->name('brand.update');
	Route::get('brand/destroy/{id}','BrandController@destroy')->name('brand.destroy');
	//brand proccess by ajax routes 

	Route::resource('category','CategoryController');
	Route::resource('subcategory','SubCategoryController');
	Route::resource('units','Unitcontroller');
	Route::resource('made-country','MadeCountryController');
	Route::resource('color','ColorController');
	Route::resource('slider','SliderController');
	Route::resource('banner','AdBannerController');
	
	//Product controller
	Route::get('product/list','ProductsController@index')->name('products.index');
	Route::get('product/create','ProductsController@index')->name('products.create');
	Route::get('product/show/{id}','ProductsController@show')->name('products.show');
	Route::get('product/edit/{id}','ProductsController@edit')->name('products.edit');
	Route::put('products/update/{id}','ProductsController@update')->name('products.update');
	Route::delete('product/destroy/{id}','ProductsController@destroy')->name('products.destroy');
	Route::get('product/approved/{id}','ProductsController@approvedProduct')->name('product.approved');
	Route::get('product/unapproved/{id}','ProductsController@unApprovedProduct')->name('product.unapproved');
	Route::get('product/pending-list','ProductsController@pendingProduct')->name('products.pending.list');


	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');

	//contact routes
	Route::get('/contact/message-seen','ContactController@seenList')->name('contact.seen.list');
	Route::get('/contact/message-unseen','ContactController@uneenList')->name('contact.unseen.list');
	Route::get('/contact/message-unseen/view/{id}','ContactController@uneenListView')->name('contact.unseen.view.list');
	Route::post('/contact/message-update/view/{id}','ContactController@uneenUpdate')->name('contact.update.list');
	Route::get('/contact/message-delete/{id}','ContactController@messageDelete')->name('contact.delete.list');
	Route::get('/contact/message/reply/{id}','ContactController@messageReply')->name('contact.reply');
	Route::get('/contact/message/reply/send','ContactController@contactReply')->name('contact.reply.send');

	//company information routes
	Route::get('/company-information','CompanyInfoControler@index')->name('company.info.index');
	Route::get('/company-information/{id}','CompanyInfoControler@edit')->name('company.info.edit');
	Route::post('/company-information/update/{id}','CompanyInfoControler@update')->name('company.info.update');

	//company logo routes
	Route::get('/company-logo','CompanyInfoControler@logoIndex')->name('company.logo.index');
	Route::get('/company-logo/{id}','CompanyInfoControler@logoEdit')->name('company.logo.edit');
	Route::post('/company-logo/update/{id}','CompanyInfoControler@logoUpdate')->name('company.logo.update');

	// subscriber routes
	Route::get('/subscribe','SubsribeController@index')->name('subscribe.index');

	// about routes
	Route::get('/about','AboutController@aboutIndex')->name('about.index');
	Route::get('/about-update/{id}','AboutController@edit')->name('about.edit');
	Route::post('/about-update/{id}','AboutController@aboutUpdate')->name('about.update');

	//user routes
	Route::get('user/','UserController@index')->name('user.index');
	Route::post('user/store','UserController@store')->name('user.store');
	Route::get('user/edit/{id}','UserController@edit')->name('user.edit');
	Route::post('user/update/{id}','UserController@update')->name('user.update');

	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');
	Route::post('password/setting/update','SettingController@userPasswordUpdate')->name('user.setting.password.update');


	// default controller 
	Route::get('get-subcategory','DefaultController@getSubCateogory')->name('get.subcategory');

});

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author', 'middleware'=>['auth','author']],function(){

	Route::get('dashboard','AuthorDashboardController@index')->name('dashboard');

	//Product controller
	Route::resource('product','ProductController');
	
	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');

	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');
	Route::post('password/setting/update','SettingController@userPasswordUpdate')->name('user.setting.password.update');

	// default controller 
	Route::get('get-subcategory','DefaultController@getSubCateogory')->name('get.subcategory');

});

Route::group(['as'=>'editor.','prefix'=>'editor','namespace'=>'Editor', 'middleware'=>['auth','editor']],function(){

	Route::get('dashboard','EditorDashboardController@index')->name('dashboard');

	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    //
}

app/Http/Controllers/Admin/Unitcontroller.php
<?php

namespace App\Http\Controllers\Admin;

use Auth;
use App\Unit;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

class Unitcontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $alldata = Unit::latest()->get();
        return view('backend.admin.units.unitsIndex',compact('alldata'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:units,name',
        ]);

        $units = new Unit();

        $units->name = $request->name;
        $units->slug = str_slug($request->name);
        $units->created_by = Auth::id();
        $units->save();

        Toastr::success('Unit Created Successfull ','Success');
        return redirect()->route('admin.units.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editData = Unit::where('id', $id)->first();
        return view('backend.admin.units.unitsEdit',compact('editData'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|unique:units,name',
        ]);

        $units = Unit::find($id);

        $units->name = $request->name;
        $units->slug = str_slug($request->name);
        $units->updated_by = Auth::id();
        $units->update();

        Toastr::success('Unit Updated Successfull ','Success');
        return redirect()->route('admin.units.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/admin/units/unitsEdit.blade.php
@extends('backend.master')

@section('title')
	Units update 
@endsection

@section('heading')
	Units Manage
@endsection

@section('mainsection')
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-12">
		<div class="card">
	        <div class="card-header">
	          <h3 class="card-title">Units Updated</h3>
	          <a href="{{ route('admin.units.index') }}" type="button" class="btn btn-success float-right"><i class="fa fa-list"></i> Units List</a>
	        </div>
	        <!-- /.card-header -->
	        <div class="card-body">
	          	<form action="{{ route('admin.units.update',$editData->id) }}" method="post" id="myForm">
	          		@csrf
	          		@method('PUT')
	          		<div class="form-row">
	          			<div class="form-group col-md-4">
	          				<label for="">Name </label>
	          				<input type="text" name="name" id="name" class="form-control" value="{{ $editData->name }}">
	          			</div>
	          		</div>
          			<div class="form-group col-md-2">
          				<button type="submit" class="btn btn-primary">Update</button>
          			</div>
	          	</form>
	      	</div>
    	</div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function () {
	  $.validator.setDefaults({
	    submitHandler: function () {
	      alert( "Form successful submitted!" );
	    }
	  });
	  $('#myForm').validate({
	    rules: {
	      name: {
	        required: true,
	        name: true,
	      }
	    },
	    messages: {
	      name: {
	        required: "Please enter a name address",
	        name: "Please enter a vaild name address"
	      }
	    },
	    errorElement: 'span',
	    errorPlacement: function (error, element) {
	      error.addClass('invalid-feedback');
	      element.closest('.form-group').append(error);
	    },
	    highlight: function (element, errorClass, validClass) {
	      $(element).addClass('is-invalid');
	    },
	    unhighlight: function (element, errorClass, validClass) {
	      $(element).removeClass('is-invalid');
	    }
	  });
	});
</script>

</section>

@endsection

resources/views/backend/admin/units/unitsIndex.blade.php
@extends('backend.master')

@section('title')
	Unit
@endsection

@section('heading')
	Unit Manage
@endsection

@section('mainsection')
<!-- Main content -->
<section class="content">
<div class="row">
    <div class="col-12">
		<div class="card">
        <div class="card-header">
          <h3 class="card-title">Unit List</h3>
          <button onclick="formShow()" class="btn btn-primary float-right"><i class="fa fa-plus-circle"></i> Add Unit</button>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table id="datatables" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>SL.No</th>
                <th>Name</th>
                <th>Slug</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            	@foreach($alldata as $key=>$units)
        		<tr>
        			<td>{{ $key + 1 }}</td>
        			<td>{{ $units->name }}</td>
        			<td>{{ $units->slug }}</td>
        			<td>
        				<a title="Edit" href="{{ route('admin.units.edit',$units->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
        				
        			</td>
        		</tr>
            	@endforeach
          	</tbody>
       	 	</table>
      	</div>
    	</div>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
          <div class="modal-content">
          	<form action="{{ route('admin.units.store') }}" id="myForm" method="post">
          		@csrf
	            <div class="modal-header">
	              <h4 class="modal-title">Unit Created ...</h4>
	              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                <span aria-hidden="true">&times;</span>
	              </button>
	            </div>
	            <div class="modal-body">
	              <div class="form-group">
	              	<label for="name">Unit Name </label>
	              	<input type="text" name="name" id="name" class="form-control" placeholder="Unit Name">
	              </div>
	            </div>
	            <div class="modal-footer justify-content-between">
	              <button id="saveButton" type="submit" class="btn btn-primary">Save</button>
	            </div>
	          </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
      <!-- /.modal -->

</div>
</section>

<script type="text/javascript">
	function formShow(){
		$('#myModal').modal('show');
	}

	$(document).ready(function () {
	  $.validator.setDefaults({
	    submitHandler: function () {
	      alert( "Form successful submitted!" );
	    }
	  });
	  $('#myForm').validate({
	    rules: {
	      name: {
	        required: true,
	        name: true,
	      }
	    },
	    messages: {
	      name: {
	        required: "Please enter a name",
	        name: "Please enter a vaild name"
	      }
	    },
	    errorElement: 'span',
	    errorPlacement: function (error, element) {
	      error.addClass('invalid-feedback');
	      element.closest('.form-group').append(error);
	    },
	    highlight: function (element, errorClass, validClass) {
	      $(element).addClass('is-invalid');
	    },
	    unhighlight: function (element, errorClass, validClass) {
	      $(element).removeClass('is-invalid');
	    }
	  });
	});
</script>


@endsection