routes/web.php
	Route::get('customar/logout','CustomarController@cusLogout')->name('customar.logout');
	Route::get('customar/order','CustomarController@cusOrder')->name('customar.order');
	Route::get('/order-view/{id}','CustomarController@orderView')->name('customar.order.view');
	Route::get('/order-view/pdf/{id}','CustomarController@orderPdf')->name('customar.order.list.pdf');
	//customar verify
	Route::get('customar-account/verify','CustomarController@customarVerify')->name('customar.verify');
	Route::post('customar/verify-success','CustomarController@cusVerify')->name('customar.verify.completes');

	// shipping and payment 
	Route::post('/shipping-store','ShippingController@store')->name('shipping.store');
	Route::get('/payment','ShippingController@payment')->name('customar.payment');

	// contact routes
	Route::get('/contact','ContactController@index')->name('contact.index');
	Route::post('/contact-store','ContactController@store')->name('contact.store');

	// subscriber routes
	Route::post('/subscribe','SubscribeController@store')->name('subscribe.store');

	// order routes
	Route::post('/order-store/by-cash','OrderController@storeByCash')->name('order.store.by.cash');
	Route::post('/order-store/by-bkash','OrderController@storeBybkash')->name('order.store.by.bkash');

	// contact routes
	Route::get('/search-products','SearchController@searchProduct')->name('search.index');

	// default routes | about, faqs, helps, 
	Route::get('/abouts','DefaultController@aboutPages')->name('about.page');
	Route::get('/faqs','DefaultController@faqsPages')->name('faqs.page');
	Route::get('/helps','DefaultController@helpPages')->name('help.page');
	Route::get('/terms-of-use','DefaultController@termsPages')->name('termsofuse.page');
	Route::get('/privacy-policy','DefaultController@privacyPages')->name('privacy.page');


});






Auth::routes();


Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin', 'middleware'=>['auth','admin']],function(){

	Route::get('dashboard','AdminDashboardController@index')->name('dashboard');

	//brand proccess routes ajax
	Route::get('brand/list','BrandController@index')->name('brand.index');
	Route::get('brand/alldata','BrandController@allData')->name('brand.alldata');
	Route::post('brand/store','BrandController@store')->name('brand.store');
	Route::get('brand/edit/{id}','BrandController@edit')->name('brand.edit');
	Route::post('brand/update/{id}','BrandController@update')->name('brand.update');
	Route::get('brand/destroy/{id}','BrandController@destroy')->name('brand.destroy');
	//brand proccess by ajax routes 

	Route::resource('category','CategoryController');
	Route::resource('subcategory','SubCategoryController');
	Route::resource('units','Unitcontroller');
	Route::resource('made-country','MadeCountryController');
	Route::resource('color','ColorController');
	Route::resource('slider','SliderController');
	Route::resource('banner','AdBannerController');
	
	//Product controller
	Route::get('product/list','ProductsController@index')->name('products.index');
	Route::get('product/create','ProductsController@index')->name('products.create');
	Route::get('product/show/{id}','ProductsController@show')->name('products.show');
	Route::get('product/edit/{id}','ProductsController@edit')->name('products.edit');
	Route::put('products/update/{id}','ProductsController@update')->name('products.update');
	Route::delete('product/destroy/{id}','ProductsController@destroy')->name('products.destroy');
	Route::get('product/approved/{id}','ProductsController@approvedProduct')->name('product.approved');
	Route::get('product/unapproved/{id}','ProductsController@unApprovedProduct')->name('product.unapproved');
	Route::get('product/pending-list','ProductsController@pendingProduct')->name('products.pending.list');


	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');

	//contact routes
	Route::get('/contact/message-seen','ContactController@seenList')->name('contact.seen.list');
	Route::get('/contact/message-unseen','ContactController@uneenList')->name('contact.unseen.list');
	Route::get('/contact/message-unseen/view/{id}','ContactController@uneenListView')->name('contact.unseen.view.list');
	Route::post('/contact/message-update/view/{id}','ContactController@uneenUpdate')->name('contact.update.list');
	Route::get('/contact/message-delete/{id}','ContactController@messageDelete')->name('contact.delete.list');
	Route::get('/contact/message/reply/{id}','ContactController@messageReply')->name('contact.reply');
	Route::get('/contact/message/reply/send','ContactController@contactReply')->name('contact.reply.send');

	//company information routes
	Route::get('/company-information','CompanyInfoControler@index')->name('company.info.index');
	Route::get('/company-information/{id}','CompanyInfoControler@edit')->name('company.info.edit');
	Route::post('/company-information/update/{id}','CompanyInfoControler@update')->name('company.info.update');

	//company logo routes
	Route::get('/company-logo','CompanyInfoControler@logoIndex')->name('company.logo.index');
	Route::get('/company-logo/{id}','CompanyInfoControler@logoEdit')->name('company.logo.edit');
	Route::post('/company-logo/update/{id}','CompanyInfoControler@logoUpdate')->name('company.logo.update');

	// subscriber routes
	Route::get('/subscribe','SubsribeController@index')->name('subscribe.index');

	// about routes
	Route::get('/about','AboutController@aboutIndex')->name('about.index');
	Route::get('/about-update/{id}','AboutController@edit')->name('about.edit');
	Route::post('/about-update/{id}','AboutController@aboutUpdate')->name('about.update');

	//user routes
	Route::get('user/','UserController@index')->name('user.index');
	Route::post('user/store','UserController@store')->name('user.store');
	Route::get('user/edit/{id}','UserController@edit')->name('user.edit');
	Route::post('user/update/{id}','UserController@update')->name('user.update');

	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');
	Route::post('password/setting/update','SettingController@userPasswordUpdate')->name('user.setting.password.update');


	// default controller 
	Route::get('get-subcategory','DefaultController@getSubCateogory')->name('get.subcategory');

});

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author', 'middleware'=>['auth','author']],function(){

	Route::get('dashboard','AuthorDashboardController@index')->name('dashboard');

	//Product controller
	Route::resource('product','ProductController');
	
	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');

	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');
	Route::post('password/setting/update','SettingController@userPasswordUpdate')->name('user.setting.password.update');

	// default controller 
	Route::get('get-subcategory','DefaultController@getSubCateogory')->name('get.subcategory');

});

Route::group(['as'=>'editor.','prefix'=>'editor','namespace'=>'Editor', 'middleware'=>['auth','editor']],function(){

	Route::get('dashboard','EditorDashboardController@index')->name('dashboard');

	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');


	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');

app/Http/Controllers/Editor/CustomarController.php
<?php

namespace App\Http\Controllers\Editor;

use App\Customar;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

class CustomarController extends Controller
{
    public function index()
    {
    	$data['alldata'] = Customar::where('status','1')->get();
    	return view('backend.editor.customar.cusindex',$data);
    }

    public function unverifyList()
    {
    	$data['alldata'] = Customar::where('status','0')->get();
    	return view('backend.editor.customar.cusUnverifylist',$data);
    }

    public function customarDestroy($id)
    {
    	$customar = Customar::find($id)->delete();
    	Toastr::success('Customar Deleted Successfull','Success');
    	return redirect()->route('editor.customar.unverify.list');
    }
}

app/Http/Controllers/Editor/EditorDashboardController.php
<?php

namespace App\Http\Controllers\Editor;

use App\User;
use App\Brand;
use App\Order;
use App\Contact;
use App\Product;
use App\Category;
use App\Customar;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EditorDashboardController extends Controller
{
    public function index()
    {
    	$data['user_count'] = User::all();
    	$data['order_count'] = Order::all();
    	$data['brand_count'] = Brand::all();
    	$data['contact_count'] = Contact::all();
    	$data['product_count'] = Product::all();
    	$data['category_count'] = Category::all();
    	$data['customar_count'] = Customar::all();
    	$data['some_orders'] = Order::latest()->take(7)->get();
    	return view('backend.editor.dashboard',$data);
    }
}

app/Http/Controllers/Editor/OrderController.php
<?php

namespace App\Http\Controllers\Editor;

use DB;
use Auth;
use App\Product;
use App\Checkout;
use App\Order;
use App\Payment;
use App\OrderDetail;
use App\SubCategory;
use App\ProductColor;
use App\ProductSubImage;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

class OrderController extends Controller
{
    public function orderPendingList()
    {
    	$alldata = Order::where('status','0')->get();
    	return view('backend.editor.order.orderPending',compact('alldata'));
    }

    public function orderApproveList()
    {
    	$alldata = Order::where('status','1')->get();
    	return view('backend.editor.order.orderApprove',compact('alldata'));
    }

    public function orderApproval($id)
    {
    	$data['invoiceOrder'] = Order::where('id', $id)->first();
    	return view('backend.editor.order.approveInvoice',$data);
    }

    public function orderApproveUpdate(Request $request, $id)
    {
    	$orderApprove = Order::find($id);
    	$orderApprove->status = '1';
    	$orderApprove->update();
    	return redirect()->route('editor.order.approve');
    }
}

app/Http/Controllers/Editor/SettingController.php
<?php

namespace App\Http\Controllers\Editor;


use Hash;
use Auth;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Brian2694\Toastr\Facades\Toastr;

class SettingController extends Controller
{
        public function userProfile()
    {
    	$userData = User::find(Auth::id());
    	return view('backend.editor.setting.profile',compact('userData'));
    }

    public function userUpdate(Request $request, $id)
    {
    	$this->validate($request, [
    		'name' => 'required',
    		'email' => 'required',
    		'address' => 'required',
    		'image' => 'mimes:jpe,jpeg,png',
    		'details' => 'required',
    	]);

    	$userUpdate = User::find(Auth::id());

    	$userUpdate->name = $request->name;
    	$userUpdate->email = $request->email;
    	$userUpdate->address = $request->address;
    	$userUpdate->details = $request->details;

    	$image = $request->file('image');
    	if($image){
    		$imagename = str_slug($request->name).'-'.uniqid().'.'.$image->getClientOriginalExtension();
    		$image->move('upload/userImage/',$imagename);

    		if(file_exists('upload/userImage/'.$userUpdate->image)){
    			unlink('upload/userImage/'.$userUpdate->image);
    		}
    		$userUpdate->image = $imagename;
    	}

    	$userUpdate->save();

    	Toastr::success('User Profile Successfull ','Success');
    	return redirect()->back();
    }

    public function userPassword()
    {
    	return view('backend.editor.setting.passwordChange');
    }

    public function userPasswordUpdate(Request $request)
    {
    	$this->validate($request, [
    		'old_password' => 'required',
    		'password' => 'required|confirmed'
    	]);

    	$hasPassword = Auth::user()->password;

    	if(Hash::check($request->old_password, $hasPassword))
    	{
    		if(!Hash::check($request->password, $hasPassword))
    		{
    			$user = User::find(Auth::id());
    			$user->password = Hash::make($request->password);
    			$user->save();
    			Toastr::success('Password Successfull Change','Success');
    			Auth::logout();
    			return redirect()->back();
                
    		}else{
    			Toastr::error('New Password Cannot be Old Password','Error');
    			return redirect()->back();
    		}
    	}else{
    		Toastr::error('Old Password Not Match','Error');
    		return redirect()->back();
    	}

    }
}

resources/views/backend/editor/dashboard.blade.php
@extends('backend.master')

@section('title')
  Dashboard
@endsection

@section('heading')
  Dashboard
@endsection

@section('mainsection')

 <section class="content">
      <div class="container-fluid">
        <!-- Info boxes -->
        <div class="row">
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box">
              <span class="info-box-icon bg-info elevation-1"><i class="fas fa-industry"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Products</span>
                <span class="info-box-number">
                  {{ count($product_count) }}
                </span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-users"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Customar</span>
                <span class="info-box-number">{{ count($customar_count) }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->

          <!-- fix for small devices only -->
          <div class="clearfix hidden-md-up"></div>

          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Order</span>
                <span class="info-box-number">{{ count($order_count) }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
          <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
              <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-user"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">User</span>
                <span class="info-box-number">{{ count($user_count) }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->

        <!-- Main row -->
        <div class="row">
          <!-- Left col -->
          <div class="col-md-8">
            <!-- TABLE: LATEST ORDERS -->
            <div class="card">
              <div class="card-header border-transparent">
                <h3 class="card-title">Latest Orders</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <div class="table-responsive">
                  <table class="table m-0">
                    <thead>
                    <tr>
                      <th>Order ID</th>
                      <th>Date</th>
                      <th>Total Amount</th>
                      <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                      @foreach($some_orders as $orders)
                      <tr>
                        <td><a href="{{ route('editor.order.approval.check',$orders->id) }}" target="_blank">OR-{{ $orders->order_no }}</a></td>
                        <td>{{ date('d-m-Y',strtotime($orders->order_date)) }}</td>
                        <td>{{ $orders->order_total }}</td>
                        <td>
                          @if($orders->status == true)
                            <span class="badge badge-success">success</span>
                          @else
                            <span class="badge badge-danger">Pending</span>
                          @endif
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
                <!-- /.table-responsive -->
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <a href="{{ route('editor.order.pending') }}" class="btn btn-sm btn-danger float-left">Pending Order</a>
                <a href="{{ route('editor.order.approve') }}" class="btn btn-sm btn-primary float-right">View All Orders</a>
              </div>
              <!-- /.card-footer -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->

          <div class="col-md-4">
            <!-- Info Boxes Style 2 -->
            <div class="info-box mb-3 bg-warning">
              <span class="info-box-icon"><i class="fas fa-tag"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Category</span>
                <span class="info-box-number">{{ count($category_count)}}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
            <div class="info-box mb-3 bg-success">
              <span class="info-box-icon"><i class="far fa-heart"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Brand</span>
                <span class="info-box-number">{{ count($brand_count)}}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <div class="info-box mb-3 bg-info">
              <span class="info-box-icon"><i class="far fa-comment"></i></span>

              <div class="info-box-content">
                <span class="info-box-text">Contact Messages</span>
                <span class="info-box-number">{{ count($contact_count) }}</span>
              </div>
              <!-- /.info-box-content -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!--/. container-fluid -->
    </section>

@endsection