routes/web.php
	Route::post('customar/profile-update','CustomarController@cusProfileUpdate')->name('customar.profile.update');
	Route::get('customar/password-change','CustomarController@cusPassword')->name('customar.password');
	Route::post('customar/password-change/update','CustomarController@cusPasswordUpdate')->name('customar.password.update');
	Route::post('customar/store','CustomarController@store')->name('customar.store');
	Route::get('customar/login','CustomarController@cusLogin')->name('customar.cuslogin');
	Route::get('customar/logout','CustomarController@cusLogout')->name('customar.logout');
	Route::get('customar/order','CustomarController@cusOrder')->name('customar.order');
	Route::get('/order-view/{id}','CustomarController@orderView')->name('customar.order.view');
	Route::get('/order-view/pdf/{id}','CustomarController@orderPdf')->name('customar.order.list.pdf');
	//customar verify
	Route::get('customar-account/verify','CustomarController@customarVerify')->name('customar.verify');
	Route::post('customar/verify-success','CustomarController@cusVerify')->name('customar.verify.completes');

	// shipping and payment 
	Route::post('/shipping-store','ShippingController@store')->name('shipping.store');
	Route::get('/payment','ShippingController@payment')->name('customar.payment');

	// contact routes
	Route::get('/contact','ContactController@index')->name('contact.index');
	Route::post('/contact-store','ContactController@store')->name('contact.store');

	// subscriber routes
	Route::post('/subscribe','SubscribeController@store')->name('subscribe.store');

	// order routes
	Route::post('/order-store/by-cash','OrderController@storeByCash')->name('order.store.by.cash');
	Route::post('/order-store/by-bkash','OrderController@storeBybkash')->name('order.store.by.bkash');

	// contact routes
	Route::get('/search-products','SearchController@searchProduct')->name('search.index');

	// default routes | about, faqs, helps, 
	Route::get('/abouts','DefaultController@aboutPages')->name('about.page');
	Route::get('/faqs','DefaultController@faqsPages')->name('faqs.page');
	Route::get('/helps','DefaultController@helpPages')->name('help.page');
	Route::get('/terms-of-use','DefaultController@termsPages')->name('termsofuse.page');
	Route::get('/privacy-policy','DefaultController@privacyPages')->name('privacy.page');


});






Auth::routes();


Route::group(['as'=>'admin.','prefix'=>'admin','namespace'=>'Admin', 'middleware'=>['auth','admin']],function(){

	Route::get('dashboard','AdminDashboardController@index')->name('dashboard');

	//brand proccess routes ajax
	Route::get('brand/list','BrandController@index')->name('brand.index');
	Route::get('brand/alldata','BrandController@allData')->name('brand.alldata');
	Route::post('brand/store','BrandController@store')->name('brand.store');
	Route::get('brand/edit/{id}','BrandController@edit')->name('brand.edit');
	Route::post('brand/update/{id}','BrandController@update')->name('brand.update');
	Route::get('brand/destroy/{id}','BrandController@destroy')->name('brand.destroy');
	//brand proccess by ajax routes 

	Route::resource('category','CategoryController');
	Route::resource('subcategory','SubCategoryController');
	Route::resource('units','Unitcontroller');
	Route::resource('made-country','MadeCountryController');
	Route::resource('color','ColorController');
	Route::resource('slider','SliderController');
	Route::resource('banner','AdBannerController');
	
	//Product controller
	Route::get('product/list','ProductsController@index')->name('products.index');
	Route::get('product/create','ProductsController@index')->name('products.create');
	Route::get('product/show/{id}','ProductsController@show')->name('products.show');
	Route::get('product/edit/{id}','ProductsController@edit')->name('products.edit');
	Route::put('products/update/{id}','ProductsController@update')->name('products.update');
	Route::delete('product/destroy/{id}','ProductsController@destroy')->name('products.destroy');
	Route::get('product/approved/{id}','ProductsController@approvedProduct')->name('product.approved');
	Route::get('product/unapproved/{id}','ProductsController@unApprovedProduct')->name('product.unapproved');
	Route::get('product/pending-list','ProductsController@pendingProduct')->name('products.pending.list');


	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');

	//contact routes
	Route::get('/contact/message-seen','ContactController@seenList')->name('contact.seen.list');
	Route::get('/contact/message-unseen','ContactController@uneenList')->name('contact.unseen.list');
	Route::get('/contact/message-unseen/view/{id}','ContactController@uneenListView')->name('contact.unseen.view.list');
	Route::post('/contact/message-update/view/{id}','ContactController@uneenUpdate')->name('contact.update.list');
	Route::get('/contact/message-delete/{id}','ContactController@messageDelete')->name('contact.delete.list');
	Route::get('/contact/message/reply/{id}','ContactController@messageReply')->name('contact.reply');
	Route::get('/contact/message/reply/send','ContactController@contactReply')->name('contact.reply.send');

	//company information routes
	Route::get('/company-information','CompanyInfoControler@index')->name('company.info.index');
	Route::get('/company-information/{id}','CompanyInfoControler@edit')->name('company.info.edit');
	Route::post('/company-information/update/{id}','CompanyInfoControler@update')->name('company.info.update');

	//company logo routes
	Route::get('/company-logo','CompanyInfoControler@logoIndex')->name('company.logo.index');
	Route::get('/company-logo/{id}','CompanyInfoControler@logoEdit')->name('company.logo.edit');
	Route::post('/company-logo/update/{id}','CompanyInfoControler@logoUpdate')->name('company.logo.update');

	// subscriber routes
	Route::get('/subscribe','SubsribeController@index')->name('subscribe.index');

	// about routes
	Route::get('/about','AboutController@aboutIndex')->name('about.index');
	Route::get('/about-update/{id}','AboutController@edit')->name('about.edit');
	Route::post('/about-update/{id}','AboutController@aboutUpdate')->name('about.update');

	//user routes
	Route::get('user/','UserController@index')->name('user.index');
	Route::post('user/store','UserController@store')->name('user.store');
	Route::get('user/edit/{id}','UserController@edit')->name('user.edit');
	Route::post('user/update/{id}','UserController@update')->name('user.update');

	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');
	Route::post('password/setting/update','SettingController@userPasswordUpdate')->name('user.setting.password.update');


	// default controller 
	Route::get('get-subcategory','DefaultController@getSubCateogory')->name('get.subcategory');

});

Route::group(['as'=>'author.','prefix'=>'author','namespace'=>'Author', 'middleware'=>['auth','author']],function(){

	Route::get('dashboard','AuthorDashboardController@index')->name('dashboard');

	//Product controller
	Route::resource('product','ProductController');
	
	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');
	Route::delete('customar/destroy/{id}','CustomarController@customarDestroy')->name('customar.destroy');

	// user setting routes
	Route::get('profile/setting','SettingController@userProfile')->name('user.setting.profile');
	Route::post('profile/setting/update/{id}','SettingController@userUpdate')->name('user.setting.profile.update');
	Route::get('password/setting','SettingController@userPassword')->name('user.setting.password');
	Route::post('password/setting/update','SettingController@userPasswordUpdate')->name('user.setting.password.update');

	// default controller 
	Route::get('get-subcategory','DefaultController@getSubCateogory')->name('get.subcategory');

});

Route::group(['as'=>'editor.','prefix'=>'editor','namespace'=>'Editor', 'middleware'=>['auth','editor']],function(){

	Route::get('dashboard','EditorDashboardController@index')->name('dashboard');

	//order routes
	Route::get('order/pending-list','OrderController@orderPendingList')->name('order.pending');
	Route::get('order/approve-list','OrderController@orderApproveList')->name('order.approve');
	Route::get('order/approval/{id}','OrderController@orderApproval')->name('order.approval.check');
	Route::post('order/pproval/{id}','OrderController@orderApproveUpdate')->name('order.approval.update');

	//customar routes
	Route::get('customar/list','CustomarController@index')->name('customar.index');
	Route::get('customar/unverify-list','CustomarController@unverifyList')->name('customar.unverify.list');

app/AdBanner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AdBanner extends Model
{
    //
}

app/Http/Controllers/Admin/AdBannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\AdBanner;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdBannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $alldata = AdBanner::all();
        return view('backend.admin.adbanner.bannerIndex',compact('alldata'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'heading1' => 'required',
            'heading2' => 'required',
            'pra1' => 'required',
            'pra2' => 'required',
            'image' => 'required|mimes:jpeg,jpg,png',
        ]);

        $banner = new AdBanner();

        $banner->heading1 = $request->heading1;
        $banner->heading2 = $request->heading2;
        $banner->pra1 = $request->pra1;
        $banner->pra2 = $request->pra2;

        $image = $request->file('image');
        if($image){
            $imagename = uniqid().'.'.$image->getClientOriginalExtension();
            $image->move('upload/banner/',$imagename);
            $banner->image = $imagename;
        }
        $banner->save();

        return redirect()->route('admin.banner.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $editData = AdBanner::where('id',$id)->first();
        return view('backend.admin.adbanner.bannerEdit',compact('editData'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'heading1' => 'required',
            'heading2' => 'required',
            'pra1' => 'required',
            'pra2' => 'required',
            'image' => 'mimes:jpeg,jpg,png',
        ]);

        $banner = AdBanner::find($id);

        $banner->heading1 = $request->heading1;
        $banner->heading2 = $request->heading2;
        $banner->pra1 = $request->pra1;
        $banner->pra2 = $request->pra2;

        $image = $request->file('image');
        if($image){
            $imagename = uniqid().'.'.$image->getClientOriginalExtension();
            $image->move('upload/banner/',$imagename);
            unlink('upload/banner/'.$banner->image);
            $banner->image = $imagename;
        }

        $banner->update();

        return redirect()->route('admin.banner.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/admin/adbanner/bannerEdit.blade.php
@extends('backend.master')

@section('title')
	Banner update 
@endsection

@section('heading')
	Banner Manage
@endsection

@section('mainsection')
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-12">
		<div class="card">
	        <div class="card-header">
	          <h3 class="card-title">Banner Updated</h3>
	          <a href="{{ route('admin.banner.index') }}" type="button" class="btn btn-success float-right"><i class="fa fa-list"></i> Banner List</a>
	        </div>
	        <!-- /.card-header -->
	        <div class="card-body">
	          	<form action="{{ route('admin.banner.update',$editData->id) }}" method="post" id="myForm" enctype="multipart/form-data">
	          		@csrf
	          		@method('PUT')
	          		<div class="form-row">
	          			<div class="form-group col-md-4">
			              	<label for="name">Heading One </label>
			              	<input type="text" name="heading1" id="heading1" class="form-control" value="{{ $editData->heading1 }}">
			            </div>
			            <div class="form-group col-md-4">
			              	<label for="name">Heading Two </label>
			              	<input type="text" name="heading2" id="heading2" class="form-control" value="{{ $editData->heading2 }}">
			            </div>
			            <div class="form-group col-md-4">
			              	<label for="name">Paragraph One </label>
			              	<input type="text" name="pra1" id="pra1" class="form-control" value="{{ $editData->pra1 }}">
			            </div>
			            <div class="form-group col-md-4">
			              	<label for="name">Paragraph Two </label>
			              	<input type="text" name="pra2" id="pra2" class="form-control" value="{{ $editData->pra2 }}">
			            </div>
			            <div class="form-group col-md-4">
			              	<label for="name">Image </label>
			              	<input type="file" name="image" id="image" class="form-control">
			            </div>
			            <div class="form-group col-md-4">
			            	<img src="{{ asset('upload/banner/'.$editData->image) }}" alt="" height="60px" width="60px">
			            </div>
	          		</div>
          			<div class="form-group col-md-2">
          				<button type="submit" class="btn btn-primary">Update</button>
          			</div>
	          	</form>
	      	</div>
    	</div>
    </div>
</div>

</section>

@endsection

resources/views/backend/admin/adbanner/bannerIndex.blade.php
@extends('backend.master')

@section('title')
	Banner
@endsection

@section('heading')
	Banner Manage
@endsection

@section('mainsection')
<!-- Main content -->
<section class="content">
<div class="row">
    <div class="col-12">
		<div class="card">
        <div class="card-header">
          <h3 class="card-title">Banner List</h3>
          @if(count($alldata) > 0)

          @else
          <button onclick="formShow()" class="btn btn-primary float-right"><i class="fa fa-plus-circle"></i> Add Banner</button>
          @endif
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table id="datatables" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>SL.No</th>
                <th>Heading One</th>
                <th>Heading Two</th>
                <th>Pra1</th>
                <th>Pra2</th>
                <th>Image</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
            	@foreach($alldata as $key=>$banner)
        		<tr>
        			<td>{{ $key + 1 }}</td>
        			<td>{{ $banner->heading1 }}</td>
        			<td>{{ $banner->heading2 }}</td>
        			<td>{{ $banner->pra1 }}</td>
        			<td>{{ $banner->pra2 }}</td>
        			<td><img src="{{ asset('upload/banner/'.$banner->image) }}" alt="" height="70px" width="70px"></td>
        			<td>
        				<a title="Edit" href="{{ route('admin.banner.edit',$banner->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
        				
        			</td>
        		</tr>
            	@endforeach
          	</tbody>
       	 	</table>
      	</div>
    	</div>
    </div>

    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
          <div class="modal-content">
          	<form action="{{ route('admin.banner.store') }}" id="myForm" method="post" enctype="multipart/form-data">
          		@csrf
	            <div class="modal-header">
	              <h4 class="modal-title">Banner Created ...</h4>
	              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	                <span aria-hidden="true">&times;</span>
	              </button>
	            </div>
	            <div class="modal-body">
	              <div class="form-group">
	              	<label for="name">Heading One </label>
	              	<input type="text" name="heading1" id="heading1" class="form-control" placeholder="Heading One">
	              </div>
	              <div class="form-group">
	              	<label for="name">Heading Two </label>
	              	<input type="text" name="heading2" id="heading2" class="form-control" placeholder="Heading Two">
	              </div>
	              <div class="form-group">
	              	<label for="name">Paragraph One </label>
	              	<input type="text" name="pra1" id="pra1" class="form-control" placeholder="Paragraph One">
	              </div>
	              <div class="form-group">
	              	<label for="name">Paragraph Two </label>
	              	<input type="text" name="pra2" id="pra2" class="form-control" placeholder="Paragraph Two">
	              </div>
	              <div class="form-group">
	              	<label for="name">Image </label>
	              	<input type="file" name="image" id="image" class="form-control">
	              </div>
	            </div>
	            <div class="modal-footer justify-content-between">
	              <button id="saveButton" type="submit" class="btn btn-primary">Save</button>
	            </div>
	          </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
      <!-- /.modal -->

</div>
</section>

<script type="text/javascript">
	function formShow(){
		$('#myModal').modal('show');
	}

</script>


@endsection